global:
  scrape_interval: 15s
  external_labels:
      monitor: 'project-monitor'

# static_configs:
#     - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100', 'nginx-exporter:9113']


  configs:
  - name: integrations
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: integrations/ntua-streaming-iot
        static_configs:
          - targets: ['ntua-streaming-iot:10000']
        metrics_path: /actuator/metrics
    remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: 704101
        password: eyJrIjoiZDE5YTY3OWM3ZWNhYzRjZGU3MjdkZjE2ZDQ2NDM5NzU3NzNkYmE3ZCIsIm4iOiJzcGJvb3QtcHJvbSIsImlkIjo3NjU3MjN9