global:
  scrape_interval: 15s
  external_labels:
      monitor: 'project-monitor'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'spboot-ntua-streaming-iot'
    metrics_path: '/streaming-iot/manage/prometheus'
    #metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['streaming_iot:10000']
      - targets: ['172.17.0.1:10000']
#      - targets: ['10.0.2.15:10000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'influxdb2'
    static_configs:
      - targets: ['influxdb2:8086']

  - job_name: 'kafka'
    static_configs:
    - targets: ['jmx-kafka:5556']

#      - targets: ['jmx-kafka:5556','jmx-kafka102:5556', 'jmx-kafka103:5556']