global:
  scrape_interval: 15s
  external_labels:
      monitor: 'project-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'spboot-ntua-streaming-iot'
    metrics_path: '/manage/prometheus'
    #metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['streaming_iot:10000']

  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets: ['node-exporter:9100']

