apiVersion: 1

# tells grafana where to find the prometheus connection
datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    user: admin
    password: admin
    url: http://localhost:9090


