apiVersion: 1

# tells grafana where to find the prometheus connection
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    user: admin
    password: admin
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    uid: prometheus
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:8080
    jsonData:
      graphiteVersion: '1.1'
  - name: InfluxDB_v2_Flux # for flux
    type: influxdb
    user: admin
    password: mySecurePassword
    access: proxy
    url: http://influxdb2:8086
    secureJsonData:
      token: jSR6OM0zJplfwrs_OCHf88rlb1ClA1v46fz8PxVOLsYrANQoixVqZrqCC9iF-QWDCVnRjaa5jtK4OwBw7-skag==
    jsonData:
      version: Flux
      organization: ntua
      defaultBucket: streaming_iot
      tlsSkipVerify: true
  - name: InfluxDB_v2_InfluxQL # for ql
    type: influxdb
    user: admin
    password: mySecurePassword
    access: proxy
    url: http://influxdb2:8086
    # This database should be mapped to a bucket
    database: streaming_iot
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token jSR6OM0zJplfwrs_OCHf88rlb1ClA1v46fz8PxVOLsYrANQoixVqZrqCC9iF-QWDCVnRjaa5jtK4OwBw7-skag=='
  - name: Loki-Spring-Logs
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
