apiVersion: 1

# tells grafana where to find the prometheus connection
datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    user: admin
    password: admin
    url: http://localhost:9090
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    jsonData:
      graphiteVersion: '1.1'
  - name: InfluxDB_v2_Flux # for flux
    type: influxdb
    access: proxy
    url: http://localhost:8086
    secureJsonData:
      token: token
    jsonData:
      version: Flux
      organization: organization
      defaultBucket: bucket
      tlsSkipVerify: true
  - name: InfluxDB_v2_InfluxQL # for ql
    type: influxdb
    access: proxy
    url: http://localhost:8086
    # This database should be mapped to a bucket
    database: site
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token <token>'